apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: webapp
spec:
  containers:
    - name: webserver-images
      image: 652801942056.dkr.ecr.us-east-1.amazonaws.com/webserver-images:v0.1
      env:
        - name: DBPWD
          value: pw
        - name: DBUSER
          value: root
        - name: DBHOST
          value: ip-pod
        - name: DBPORT
          value: "3306"
      ports:
        - containerPort: 8080