apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: webapp
spec:
  containers:
    - name: webserver-images
      image: 
      env:
        - name: DBPWD
          value: pw
        - name: DBUSER
          value: root
        - name: DBHOST
          value: 10.244.0.11
        - name: DBPORT
          value: "3306"
      ports:
        - containerPort: 8080