apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app
  namespace: webapp
  labels:
    app: employees
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
        - name: webserver-images
          image: 652801942056.dkr.ecr.us-east-1.amazonaws.com/webserver-images:v0.1
          env:
            - name: DBPWD
              value: pw
            - name: DBUSER
              value: root
            - name: DBHOST
              value: "mysql.sqldb.svc.cluster.local"
            - name: DBPORT
              value: "3306"
          ports:
            - containerPort: 8080
