apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: sqldb
spec:
  containers:
    - name: mysql-images
      image: 652801942056.dkr.ecr.us-east-1.amazonaws.com/mysql-images:v0.1
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
      ports:
        - containerPort: 3306
